#!/bin/bash
set -eo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/../../../" && pwd)"
if [ ! -f "$ROOT_DIR/.build-compile/nrx" ]; then
  (cd $ROOT_DIR && pnpm nrz-build --bins=nrx --outdir=".build-compile" compile > /dev/null 2>&1)
fi
"$ROOT_DIR/.build-compile/nrx" "$@"
