#!/bin/bash
set -eo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/../../../" && pwd)"
if [ ! -f "$ROOT_DIR/.build-bundle/nrr.js" ]; then
  (cd $ROOT_DIR && pnpm nrz-build --bins=nrr --outdir=".build-bundle" bundle > /dev/null 2>&1)
fi
deno -A "$ROOT_DIR/.build-bundle/nrr.js" "$@"
